// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RiyBhQzkSTF7YgvC1l4KS7q7Df088k4',
    appId: '1:276822094809:web:6a7e46bbacac6099069fc8',
    messagingSenderId: '276822094809',
    projectId: 'fir-kanda',
    authDomain: 'fir-kanda.firebaseapp.com',
    storageBucket: 'fir-kanda.appspot.com',
    measurementId: 'G-9EQMC5HVDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoHNBfjnHXF8mcpRL4xrKGAiXSBUXDf8o',
    appId: '1:276822094809:android:b5a4240aa0c9b513069fc8',
    messagingSenderId: '276822094809',
    projectId: 'fir-kanda',
    storageBucket: 'fir-kanda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA96IcAB0u3oW5ICWdNMXOPeSDlehTleTc',
    appId: '1:276822094809:ios:8ae80cbf7a9a0fd2069fc8',
    messagingSenderId: '276822094809',
    projectId: 'fir-kanda',
    storageBucket: 'fir-kanda.appspot.com',
    iosBundleId: 'com.example.firebaseKanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA96IcAB0u3oW5ICWdNMXOPeSDlehTleTc',
    appId: '1:276822094809:ios:e85560b245e40b66069fc8',
    messagingSenderId: '276822094809',
    projectId: 'fir-kanda',
    storageBucket: 'fir-kanda.appspot.com',
    iosBundleId: 'com.example.firebaseKanda.RunnerTests',
  );
}
